mapping:
  VideoStream:
    args:
      webcam_id: 1
    processors:
    - FaceLandmarkProcessor:
        processors:
        - LandmarkEuroFilter:
            args:
              beta: 0
              min_cutoff: 1
            triggers:
            - RelativeCursorControl:
                action:
                - MoveMouse
                args:
                  velocity_compensation_x: 0.05
                  velocity_compensation_y: 0.5
                  x_threshold: 0.02
                  y_threshold: 0.03
        triggers:
        - RegionOfInterest:
            action:
            - Logger
            args:
              landmarks:
              - 1
              position:
              - 0
              - 0
              size:
              - 0.3
              - 0.3
        - LandmarkDistance:
            action:
            - MouseClick:
                args:
                  key_name: left_down
            args:
              landmarks:
              - 12
              - 15
              threshold: 0.02
        - LandmarkDistance:
            action:
            - MouseClick:
                args:
                  key_name: left_up
            args:
              direction: smaller
              landmarks:
              - 12
              - 15
              threshold: 0.02
        - LandmarkDistance:
            action:
            - MouseClick:
                args:
                  key_name: right
            args:
              direction: smaller
              landmarks:
              - 61
              - 291
              threshold: 0.09
version: 1.2
