version: 1.2
mapping:
  VideoStream:
    args:
      webcam_id: 0
    processors:
      - FaceLandmarkProcessor:
          triggers:
            - LandmarkDistance: # mouth open
                args:
                  landmark1: 12
                  landmark2: 15
                  threshold: 0.05
                action:
                  - MouseClick:
                      args:
                        key_name: "left"