from ctrlability.triggers.landmark_distance import LandmarkDistance
from ctrlability.triggers.relative_cursor_control import RelativeCursorControl
from ctrlability.triggers.throughput import Throughput
